### ISSUE TITLE
Mixtral update

### ISSUE THREAD

**Issue by pseudotensor** [jllllll/llama-cpp-python-cuBLAS-wheels#34]
llama-cpp-python 0.2.23 has updated llama.cpp that works for mixtral, can we get new builds? Thanks!

**Comment by jllllll** [comment]
Wheels are being made now.

**Comment by gaby** [comment]
Looking forward! @jllllll Thank you! 💪

**Comment by jllllll** [comment]
Been having some difficulties getting wheels built, but it should get done eventually.
Had to cut out MacOS 11 wheels for now and may need to cut out Windows ROCm wheels until I can figure out what's wrong.

**Comment by oobabooga** [comment]
I experienced the same issues yesterday/today with the ROCm wheels. The problem seems to consistently happen for target

```
windows-latest AVX ROCm 5.5.1 Wheel 3.11
```

with error

```
CMake Error at CMakeLists.txt:40 (endif):
  Flow control statements are not properly nested.
```

Examples:

https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/actions/runs/7211477664/job/19649407361#logs
https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/actions/runs/7211523284/job/19649458525

ROCm 5.4.2 seems to work on Ubuntu:

https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/actions/runs/7211477664/job/19649408015
https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/actions/runs/7211523284/job/19649426257

That's not very informative but it's what I have been able to gather.

**Comment by jllllll** [comment]
@oobabooga 
0.2.23 wheels have finished building and uploading, excluding the MacOS 11 and Windows ROCm wheels.
I'll look into fixing the ROCm wheel issue as it seems to be more of a typo than anything major.
I have no idea what is wrong with the MacOS 11 wheels though. It doesn't give me any real error messages to work off of.

**Comment by oobabooga** [comment]
Thank you so much @jllllll. I have pushed an update at https://github.com/oobabooga/text-generation-webui/pull/4930 and confirmed that all wheels are up except for the MacOS 11 ones.

I wasn't aware that there were ROCm llama.cpp wheels for Windows; these are not included in the requirements*.txt at the moment.

**Comment by gaby** [comment]
@pseudotensor This can be closed now
