### ISSUE TITLE
Request upgrade: llama-cpp-python v0.2.24

### ISSUE THREAD

**Issue by gzjaychen** [jllllll/llama-cpp-python-cuBLAS-wheels#37]
Thanks.

**Comment by gaby** [comment]
👍 tracking this

**Comment by BadisG** [comment]
Yep, an upgrade would be good there, we've increased the prompt proessing speed by 3 with the new llama.cpp commits

**Comment by gaby** [comment]
Latest is now v0.2.25

**Comment by gaby** [comment]
@jllllll Any plans to do a new release?

**Comment by gzjaychen** [comment]
> @jllllll Any plans to do a new release?

According to README, you can build it by yourself first.

**Comment by BadisG** [comment]
Can't do it for llama-cpp-python-cuda though:

```
(textgen) D:\llama-cpp-python-cuBLAS-wheels>python -m pip install llama-cpp-python-cuda==0.2.25 --prefer-binary --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/textgen/AVX2/cu121
```

```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/textgen/AVX2/cu121
ERROR: Could not find a version that satisfies the requirement llama-cpp-python-cuda==0.2.25 (from versions: 0.1.73+cu121, 0.1.74+cu121, 0.1.76+cu121, 0.1.77+cu121, 0.1.78+cu121, 0.1.79+cu121, 0.1.80+cu121, 0.1.81+cu121, 0.1.82+cu121, 0.1.83+cu121, 0.1.84+cu121, 0.1.85+cu121, 0.2.0+cu121, 0.2.1+cu121, 0.2.2+cu121, 0.2.3+cu121, 0.2.4+cu121, 0.2.5+cu121, 0.2.6+cu121, 0.2.7+cu121, 0.2.8+cu121, 0.2.9+cu121, 0.2.10+cu121, 0.2.11+cu121, 0.2.14+cu121, 0.2.15+cu121, 0.2.16+cu121, 0.2.17+cu121, 0.2.18+cu121, 0.2.19+cu121, 0.2.20+cu121, 0.2.23+cu121)
ERROR: No matching distribution found for llama-cpp-python-cuda==0.2.25
```

**Comment by BadisG** [comment]
All right you can have those llama-cpp-python wheels there instead 
https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases

**Comment by gzjaychen** [comment]
> @gzjaychen Can't do it for llama-cpp-python-cuda though:
> 
> ```
> (textgen) D:\llama-cpp-python-cuBLAS-wheels>python -m pip install llama-cpp-python-cuda==0.2.25 --prefer-binary --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/textgen/AVX2/cu121
> ```
> 
> ```
> Defaulting to user installation because normal site-packages is not writeable
> Looking in indexes: https://pypi.org/simple, https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/textgen/AVX2/cu121
> ERROR: Could not find a version that satisfies the requirement llama-cpp-python-cuda==0.2.25 (from versions: 0.1.73+cu121, 0.1.74+cu121, 0.1.76+cu121, 0.1.77+cu121, 0.1.78+cu121, 0.1.79+cu121, 0.1.80+cu121, 0.1.81+cu121, 0.1.82+cu121, 0.1.83+cu121, 0.1.84+cu121, 0.1.85+cu121, 0.2.0+cu121, 0.2.1+cu121, 0.2.2+cu121, 0.2.3+cu121, 0.2.4+cu121, 0.2.5+cu121, 0.2.6+cu121, 0.2.7+cu121, 0.2.8+cu121, 0.2.9+cu121, 0.2.10+cu121, 0.2.11+cu121, 0.2.14+cu121, 0.2.15+cu121, 0.2.16+cu121, 0.2.17+cu121, 0.2.18+cu121, 0.2.19+cu121, 0.2.20+cu121, 0.2.23+cu121)
> ERROR: No matching distribution found for llama-cpp-python-cuda==0.2.25
> ```

llama-cpp-python==0.2.25
not
llama-cpp-python-cuda==0.2.25

**Comment by BadisG** [comment]
@gzjaychen I wanted the cuda one so that I can offload with the gpu but it's ok I found the wheels now

**Comment by jllllll** [comment]
Building wheels now.

**Comment by BadisG** [comment]
@jllllll I just tried this Webui Wheel: llama_cpp_python_cuda-0.2.25+cu121avx-cp311-cp311-win_amd64.whl
and I got this when trying it on ooba's webui
```
AVX = 1 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 |
```

The problem is that my intel i7 10700k can handle more architectures than just AVX and BLAS, this is what it could handle:
AVX -AVX2 - FMA - F16C - SSE3 - SSSE3

Your wheels doesn't seem to optimize CPU fully, and that's a shame because I really need those optimisations to get acceptable speed on Mixtral with CPU offloading

**Comment by gaby** [comment]
@BadisG You are installing the wrong wheel...

https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/

Use avx2 or avx512

**Comment by BadisG** [comment]
@gaby I know there's other kinds of wheels but those are for "llama-cpp-python" and not "llama-cpp-python-cuda"...
That means with those wheels I wouldn't be able to do some GPU offloading on ooba's webui

**Comment by jllllll** [comment]
@gaby `llama-cpp-python-cuda` wheels can be found here: https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/textgen

Use the `AVX2` wheels. I don't bother with building `AVX512` wheels for `llama-cpp-python-cuda` because the performance improvement is minuscule and doesn't justify the increase in build times due to the additional wheels being added to the workflow. It already takes 4 hours for each version of `llama-cpp-python` released. I am building thousands of wheels just for the main CPU configurations. I'll probably stop building `AVX512` wheels for the main package eventually as build times continue to increase.

The point of this repo isn't to provide absolute optimization, it is just for convenience. If you want to maximize performance for your system, then you should build `llama-cpp-python` yourself. There are just far too many configuration options available to justify building wheels for all of them.

You can see just how many wheels I've built here: https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/releases
Current total as of writing is `18,039`.

**Comment by BadisG** [comment]
How do I build wheels so that its name is "llama-cpp-python-cuda" at the end? That's the one ooba's webui wants if I want to have access to gpu offloading
